DROP DATABASE IF EXISTS bperan;

CREATE DATABASE bperan;

DROP TABLE IF EXISTS `bperan`.`usuario`;

CREATE TABLE  `bperan`.`usuario` (
  `IDUSUARIO` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `FECHACREACION` datetime NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;