package es.project.bperan.pojo;
// Generated 28-abr-2016 22:22:17 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private Integer idempleado;
	private Obras obras;
	private String nombre;
	private String apellidos;
	private String nif;
	private Date fechanacimiento;
	private int telefono;
	private String direccion;
	private String poblacion;
	private String provincia;
	private int codigopostal;
	private int nacionalidad;
	private int numseguridadsocial;
	private String tipocontrato;
	private Date fechaalta;
	private String estado;
	private String categoria;
	private Set bajalaborals = new HashSet(0);
	private Set vacacioneses = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String nombre, String apellidos, String nif, Date fechanacimiento, int telefono, String direccion,
			String poblacion, String provincia, int codigopostal, int nacionalidad, int numseguridadsocial,
			Date fechaalta, String estado) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nif = nif;
		this.fechanacimiento = fechanacimiento;
		this.telefono = telefono;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.provincia = provincia;
		this.codigopostal = codigopostal;
		this.nacionalidad = nacionalidad;
		this.numseguridadsocial = numseguridadsocial;
		this.fechaalta = fechaalta;
		this.estado = estado;
	}

	public Empleado(Obras obras, String nombre, String apellidos, String nif, Date fechanacimiento, int telefono,
			String direccion, String poblacion, String provincia, int codigopostal, int nacionalidad,
			int numseguridadsocial, String tipocontrato, Date fechaalta, String estado, String categoria,
			Set bajalaborals, Set vacacioneses) {
		this.obras = obras;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nif = nif;
		this.fechanacimiento = fechanacimiento;
		this.telefono = telefono;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.provincia = provincia;
		this.codigopostal = codigopostal;
		this.nacionalidad = nacionalidad;
		this.numseguridadsocial = numseguridadsocial;
		this.tipocontrato = tipocontrato;
		this.fechaalta = fechaalta;
		this.estado = estado;
		this.categoria = categoria;
		this.bajalaborals = bajalaborals;
		this.vacacioneses = vacacioneses;
	}

	public Integer getIdempleado() {
		return this.idempleado;
	}

	public void setIdempleado(Integer idempleado) {
		this.idempleado = idempleado;
	}

	public Obras getObras() {
		return this.obras;
	}

	public void setObras(Obras obras) {
		this.obras = obras;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public int getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(int codigopostal) {
		this.codigopostal = codigopostal;
	}

	public int getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(int nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public int getNumseguridadsocial() {
		return this.numseguridadsocial;
	}

	public void setNumseguridadsocial(int numseguridadsocial) {
		this.numseguridadsocial = numseguridadsocial;
	}

	public String getTipocontrato() {
		return this.tipocontrato;
	}

	public void setTipocontrato(String tipocontrato) {
		this.tipocontrato = tipocontrato;
	}

	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set getBajalaborals() {
		return this.bajalaborals;
	}

	public void setBajalaborals(Set bajalaborals) {
		this.bajalaborals = bajalaborals;
	}

	public Set getVacacioneses() {
		return this.vacacioneses;
	}

	public void setVacacioneses(Set vacacioneses) {
		this.vacacioneses = vacacioneses;
	}

}
