package es.project.bperan.pojo;
// Generated 17-may-2016 15:32:48 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Obras generated by hbm2java
 */
public class Obras implements java.io.Serializable {

	private Integer idobra;
	private String nombreobra;
	private String direccion;
	private String latitud;
	private String longitud;
	private String descripcion;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private Set empleados = new HashSet(0);
	private Set presupuestos = new HashSet(0);
	private Set fotoses = new HashSet(0);

	public Obras() {
	}

	public Obras(String nombreobra, String direccion, Date fechaInicio, Date fechaFin, String estado) {
		this.nombreobra = nombreobra;
		this.direccion = direccion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	public Obras(String nombreobra, String direccion, String latitud, String longitud, String descripcion,
			Date fechaInicio, Date fechaFin, String estado, Set empleados, Set presupuestos, Set fotoses) {
		this.nombreobra = nombreobra;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.descripcion = descripcion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.empleados = empleados;
		this.presupuestos = presupuestos;
		this.fotoses = fotoses;
	}

	public Integer getIdobra() {
		return this.idobra;
	}

	public void setIdobra(Integer idobra) {
		this.idobra = idobra;
	}

	public String getNombreobra() {
		return this.nombreobra;
	}

	public void setNombreobra(String nombreobra) {
		this.nombreobra = nombreobra;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set getPresupuestos() {
		return this.presupuestos;
	}

	public void setPresupuestos(Set presupuestos) {
		this.presupuestos = presupuestos;
	}

	public Set getFotoses() {
		return this.fotoses;
	}

	public void setFotoses(Set fotoses) {
		this.fotoses = fotoses;
	}

}
