package es.project.bperan.pojo;
// Generated 28-abr-2016 22:22:17 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Obras generated by hbm2java
 */
public class Obras implements java.io.Serializable {

	private Integer idobra;
	private String nombreobra;
	private String ubicacion;
	private String descripcion;
	private Double costeTotal;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private Set empleados = new HashSet(0);
	private Set presupuestos = new HashSet(0);
	private Set fotoses = new HashSet(0);

	public Obras() {
	}

	public Obras(String nombreobra, String ubicacion, Double costeTotal, Date fechaInicio, Date fechaFin, String estado) {
		this.nombreobra = nombreobra;
		this.ubicacion = ubicacion;
		this.costeTotal = costeTotal;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	public Obras(String nombreobra, String ubicacion, String descripcion, Double costeTotal, Date fechaInicio, Date fechaFin, String estado,
			Set empleados, Set presupuestos, Set fotoses) {
		this.nombreobra = nombreobra;
		this.ubicacion = ubicacion;
		this.descripcion = descripcion;
		this.costeTotal = costeTotal;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.empleados = empleados;
		this.presupuestos = presupuestos;
		this.fotoses = fotoses;
	}

	public Integer getIdobra() {
		return this.idobra;
	}

	public void setIdobra(Integer idobra) {
		this.idobra = idobra;
	}

	public String getNombreobra() {
		return nombreobra;
	}

	public void setNombreobra(String nombreobra) {
		this.nombreobra = nombreobra;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getCosteTotal() {
		return this.costeTotal;
	}

	public void setCosteTotal(Double costeTotal) {
		this.costeTotal = costeTotal;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set getPresupuestos() {
		return this.presupuestos;
	}

	public void setPresupuestos(Set presupuestos) {
		this.presupuestos = presupuestos;
	}

	public Set getFotoses() {
		return this.fotoses;
	}

	public void setFotoses(Set fotoses) {
		this.fotoses = fotoses;
	}

}
