package es.project.bperan.pojo;

// default package
// Generated 20-abr-2016 19:25:26 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Obras generated by hbm2java
 */
public class Obras implements java.io.Serializable {

	private Integer idobra;
	private Cliente cliente;
	private Empleado empleado;
	private String uicacion;
	private String descripcion;
	private int costeTotal;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private Set presupuestos = new HashSet(0);
	private Set fotoses = new HashSet(0);

	public Obras() {
	}

	public Obras(Cliente cliente, Empleado empleado, String uicacion, int costeTotal, Date fechaInicio, Date fechaFin,
			String estado) {
		this.cliente = cliente;
		this.empleado = empleado;
		this.uicacion = uicacion;
		this.costeTotal = costeTotal;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	public Obras(Cliente cliente, Empleado empleado, String uicacion, String descripcion, int costeTotal,
			Date fechaInicio, Date fechaFin, String estado, Set presupuestos, Set fotoses) {
		this.cliente = cliente;
		this.empleado = empleado;
		this.uicacion = uicacion;
		this.descripcion = descripcion;
		this.costeTotal = costeTotal;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.presupuestos = presupuestos;
		this.fotoses = fotoses;
	}

	public Integer getIdobra() {
		return this.idobra;
	}

	public void setIdobra(Integer idobra) {
		this.idobra = idobra;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public String getUicacion() {
		return this.uicacion;
	}

	public void setUicacion(String uicacion) {
		this.uicacion = uicacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getCosteTotal() {
		return this.costeTotal;
	}

	public void setCosteTotal(int costeTotal) {
		this.costeTotal = costeTotal;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getPresupuestos() {
		return this.presupuestos;
	}

	public void setPresupuestos(Set presupuestos) {
		this.presupuestos = presupuestos;
	}

	public Set getFotoses() {
		return this.fotoses;
	}

	public void setFotoses(Set fotoses) {
		this.fotoses = fotoses;
	}

}
