package es.project.bperan.pojo;
// Generated 23-abr-2016 18:30:53 by Hibernate Tools 5.1.0.Alpha1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer idrole;
	private String nombre;
	private String descripcion;
	private Usuario usuario;

	public Role() {
	}

	public Role(String nombre) {
		this.nombre = nombre;
	}

	public Role(String nombre, String descripcion, Usuario usuario) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.usuario = usuario;
	}

	public Integer getIdrole() {
		return this.idrole;
	}

	public void setIdrole(Integer idrole) {
		this.idrole = idrole;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
