package es.project.bperan.pojo;

// default package
// Generated 20-abr-2016 19:25:26 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	private String password;
	private Date fechacreacion;
	private Role role;

	public Usuario() {
	}

	public Usuario(String nombre, String password, Date fechacreacion, Role role) {
		this.nombre = nombre;
		this.password = password;
		this.fechacreacion = fechacreacion;
		this.role = role;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
