package es.project.bperan.pojo;
// Generated 28-abr-2016 22:22:17 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private Role role;
	private String nombre;
	private String password;
	private Date fechacreacion;
	private Set clientes = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Role role, String nombre, String password, Date fechacreacion) {
		this.role = role;
		this.nombre = nombre;
		this.password = password;
		this.fechacreacion = fechacreacion;
	}

	public Usuario(Role role, String nombre, String password, Date fechacreacion, Set clientes) {
		this.role = role;
		this.nombre = nombre;
		this.password = password;
		this.fechacreacion = fechacreacion;
		this.clientes = clientes;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
