package es.project.bperan.pojo;

// default package
// Generated 20-abr-2016 19:25:26 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	private String password;
	private Date fechacreacio;
	private String idrole;

	public Usuario() {
	}

	public Usuario(String nombre, String password, Date fechacreacio, String idrole) {
		this.nombre = nombre;
		this.password = password;
		this.fechacreacio = fechacreacio;
		this.idrole = idrole;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getFechacreacio() {
		return this.fechacreacio;
	}

	public void setFechacreacio(Date fechacreacio) {
		this.fechacreacio = fechacreacio;
	}

	public String getIdrole() {
		return this.idrole;
	}

	public void setIdrole(String idrole) {
		this.idrole = idrole;
	}

}
