package es.project.bperan.pojo;

// default package
// Generated 20-abr-2016 19:25:26 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Vacaciones generated by hbm2java
 */
public class Vacaciones implements java.io.Serializable {

	private Integer idvacaciones;
	private Empleado empleado;
	private Date fechaInicio;
	private Date fechaFin;

	public Vacaciones() {
	}

	public Vacaciones(Empleado empleado, Date fechaInicio, Date fechaFin) {
		this.empleado = empleado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Integer getIdvacaciones() {
		return this.idvacaciones;
	}

	public void setIdvacaciones(Integer idvacaciones) {
		this.idvacaciones = idvacaciones;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
